/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package davidson.tp1po;

import javax.swing.JOptionPane;

/**
 *
 * @author Davidson
 */
public class MainScreen extends javax.swing.JFrame {
    
    // <editor-fold defaultstate="collapsed" desc="Attributes">
    private SetupScreen solverScreen;
    private int startTimeHour;
    private int endTimeHour;
    private String[] hours;
    // </editor-fold>
    
    public MainScreen() {
        hours = new String[] {
            "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00",
            "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00",
            "20:00", "21:00", "22:00", "23:00"
        };
        
        initComponents();
    }
    
    // <editor-fold defaultstate="collapsed" desc="Getters">
    public int getStartTimeHour() {
        return this.startTimeHour;
    }
    
    public int getEndTimeHour() {
        return this.endTimeHour;
    }
    
    public String[] getHours() {
        return this.hours;
    }
    // </editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftSidePanel = new javax.swing.JPanel();
        textProblemScrollPane = new javax.swing.JScrollPane();
        textProblemLabel = new javax.swing.JTextArea();
        titleProblemScrollPane = new javax.swing.JScrollPane();
        titleProblemTextArea = new javax.swing.JTextArea();
        rightSidePanel = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        startTimeComboBox = new javax.swing.JComboBox<>();
        endTimeComboBox = new javax.swing.JComboBox<>();
        startTimeLabel = new javax.swing.JLabel();
        endTimeLabel = new javax.swing.JLabel();
        messageScrollPane = new javax.swing.JScrollPane();
        questionTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa Operacional - Trabalho Prático 1");
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(MAXIMIZED_BOTH);

        leftSidePanel.setBackground(new java.awt.Color(245, 245, 245));
        leftSidePanel.setPreferredSize(new java.awt.Dimension(600, 600));

        textProblemScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textProblemScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        textProblemScrollPane.setEnabled(false);
        textProblemScrollPane.setFocusable(false);

        textProblemLabel.setEditable(false);
        textProblemLabel.setBackground(new java.awt.Color(245, 245, 245));
        textProblemLabel.setColumns(20);
        textProblemLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textProblemLabel.setForeground(new java.awt.Color(102, 102, 102));
        textProblemLabel.setLineWrap(true);
        textProblemLabel.setRows(9);
        textProblemLabel.setText("As unidades acadêmicas de uma determinada universidade contratam estagiários do curso de Sistemas de Informação para prestar pequenos serviços de tecnologia.\n\nO Departamento de Computação está interessado na possibilidade e quer saber o número mínimo de estudantes que deve contratar.\n\nCada estagiário trabalha durante três horas consecutivas e nenhum deles quer começar a trabalhar ao meio-dia.");
        textProblemLabel.setWrapStyleWord(true);
        textProblemScrollPane.setViewportView(textProblemLabel);

        titleProblemScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        titleProblemScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        titleProblemScrollPane.setEnabled(false);
        titleProblemScrollPane.setFocusable(false);

        titleProblemTextArea.setEditable(false);
        titleProblemTextArea.setBackground(new java.awt.Color(245, 245, 245));
        titleProblemTextArea.setColumns(20);
        titleProblemTextArea.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        titleProblemTextArea.setForeground(new java.awt.Color(0, 153, 153));
        titleProblemTextArea.setLineWrap(true);
        titleProblemTextArea.setRows(2);
        titleProblemTextArea.setText("Ajude o Departamento de Computação a encontrar a solução do problema");
        titleProblemTextArea.setWrapStyleWord(true);
        titleProblemScrollPane.setViewportView(titleProblemTextArea);

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleProblemScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textProblemScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSidePanelLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(titleProblemScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textProblemScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        rightSidePanel.setBackground(new java.awt.Color(255, 255, 255));

        nextButton.setBackground(new java.awt.Color(255, 255, 255));
        nextButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nextButton.setForeground(new java.awt.Color(102, 102, 102));
        nextButton.setLabel("Continuar");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        startTimeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startTimeComboBox.setForeground(new java.awt.Color(102, 102, 102));
        startTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(hours));

        endTimeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        endTimeComboBox.setForeground(new java.awt.Color(102, 102, 102));
        endTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(hours));

        startTimeLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        startTimeLabel.setForeground(new java.awt.Color(102, 102, 102));
        startTimeLabel.setLabelFor(startTimeComboBox);
        startTimeLabel.setText("de: ");
        startTimeLabel.setFocusable(false);
        startTimeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        endTimeLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        endTimeLabel.setForeground(new java.awt.Color(102, 102, 102));
        endTimeLabel.setLabelFor(endTimeComboBox);
        endTimeLabel.setText("até: ");
        endTimeLabel.setFocusable(false);
        endTimeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        messageScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        messageScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        messageScrollPane.setEnabled(false);
        messageScrollPane.setFocusable(false);

        questionTextArea.setEditable(false);
        questionTextArea.setColumns(20);
        questionTextArea.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        questionTextArea.setForeground(new java.awt.Color(102, 102, 102));
        questionTextArea.setLineWrap(true);
        questionTextArea.setRows(2);
        questionTextArea.setText("Em que período os estagiários devem trabalhar?");
        questionTextArea.setWrapStyleWord(true);
        messageScrollPane.setViewportView(questionTextArea);

        javax.swing.GroupLayout rightSidePanelLayout = new javax.swing.GroupLayout(rightSidePanel);
        rightSidePanel.setLayout(rightSidePanelLayout);
        rightSidePanelLayout.setHorizontalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightSidePanelLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(endTimeLabel)
                            .addComponent(startTimeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextButton)))
                    .addComponent(messageScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        rightSidePanelLayout.setVerticalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(messageScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startTimeLabel))
                .addGap(20, 20, 20)
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endTimeLabel))
                .addGap(20, 20, 20)
                .addComponent(nextButton)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
            .addComponent(rightSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        String startTimeString = startTimeComboBox.getModel().getSelectedItem().toString();
        String endTimeString = endTimeComboBox.getModel().getSelectedItem().toString();
        
        startTimeString = startTimeString.substring(0, 2);
        endTimeString = endTimeString.substring(0, 2);
        
        this.startTimeHour = Integer.parseInt(startTimeString);
        this.endTimeHour = Integer.parseInt(endTimeString);
        
        if (this.endTimeHour - this.startTimeHour < 3) {
            Object[] options = {"Ok"};
            JOptionPane.showOptionDialog(this, "Lembre-se: os estagiários devem trabalhar por três horas cosecutivas!", "Lembrete", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        } else {
            solverScreen = new SetupScreen(this);
            solverScreen.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> endTimeComboBox;
    private javax.swing.JLabel endTimeLabel;
    private javax.swing.JPanel leftSidePanel;
    private javax.swing.JScrollPane messageScrollPane;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextArea questionTextArea;
    private javax.swing.JPanel rightSidePanel;
    private javax.swing.JComboBox<String> startTimeComboBox;
    private javax.swing.JLabel startTimeLabel;
    private javax.swing.JTextArea textProblemLabel;
    private javax.swing.JScrollPane textProblemScrollPane;
    private javax.swing.JScrollPane titleProblemScrollPane;
    private javax.swing.JTextArea titleProblemTextArea;
    // End of variables declaration//GEN-END:variables
}
